# Configs for the input paths and parameters
Path of Input:
  Super Reference: /path/to/super_reference
  Secondary List:
  - /path/to/secondary1
  - /path/to/secondary2
  - /path/to/secondary3
  DEM TIFF File: /path/to/dem.tif

Path of Output:
  Output Dict: /path/to/output_dict/

Selected Frequency and Polarization:
  Freq: A
  Pol: HH

Path of Python Interpreter:
  isce2: /path/to/isce2/bin/python
  isce3: /path/to/isce3/bin/python

Path of NISAR Workflow Software:
  NISARAPP: /path/to/NISARAPP/

# Number of parallel processes to run. Default is 8.
NumParallels: 8

# Options: 'coarse' or 'fine'.
Coregistration: fine

Number of subsequent dates: 2

Multilook Parameters:
  InSAR Range Looks: 4
  InSAR Azimuth Looks: 5
  Ion Range Looks: 40
  Ion Azimuth Looks: 50

Coherence Estimation Parameters:
  Window Size: 11

# We recommend using the Goldstein filter (psfilt). For more aggressive noise reduction, use a larger window size, a smaller window step, and a lower alpha value.
Filtering Parameters:
  Do Filtering: true
  Filter Type: psflit
  Window Size: 64
  Window Step: 16
  Alpha: 0.7

# Ion: Mainband Range Split Spectrum; 
# Trop: pyaps with ERA5; 
# SET: pysoild 
Error Correction Parameters:
  Do Ionospheric Correction: true
  Do Tropospheric Correction: true
  Do Soild Earth Tide Correction: true
